name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: docker build -t my-flask-app .

      # Step 3: Run the Docker container
      - name: Run Docker container
        run: docker run -d -p 8080:8080 my-flask-app

      # Step 4: Wait for the Flask app to start (adjust wait time if needed)
      - name: Wait for app to start
        run: sleep 10

      # Step 5: Test the Flask app by sending a request
      - name: Test app
        run: curl -sSf http://localhost:8080/

      # Step 6: Run main.py for the backend server
      - name: Run backend server
        run: python main.py
